# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  sln: "./BlackjackGame.sln"
  tests: "./MyApp.Tests/MyApp.Tests.csproj"

parameters:
  - name: operatingSystems
    type: object
    default:
      - name: Ubuntu
        vmImage: ubuntu-latest
      - name: Windows
        vmImage: windows-latest
      - name: macOS
        vmImage: macOS-latest
  - name: configurations
    type: object
    default:
      - Debug
      - Release

jobs:
  - ${{ each conf in parameters.configurations }}:
      - ${{ each os in parameters.operatingSystems }}:
          - job: job${{ os.name }}${{ conf }}
            displayName: ${{ conf }} (${{ os.name }})
            pool:
              vmImage: ${{ os.vmImage }}
            steps:
              - task: DotNetCoreCLI@2
                displayName: Build solution (${{ os.name }} ${{ conf }})
                inputs:
                  command: build
                  projects: $(sln)
                  arguments: --configuration ${{ conf }} --nologo
              - task: DotNetCoreCLI@2
                displayName: Run tests (${{ os.name }} ${{ conf }})
                inputs:
                  command: test
                  projects: $(tests)
                  arguments: --configuration ${{ conf }} --blame-hang-timeout 60sec --no-build --nologo /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
                  publishTestResults: true
              - script: "dotnet tool install --global dotnet-reportgenerator-globaltool"
                displayName: "Install ReportGenerator tool"
              - script: 'reportgenerator -reports:**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverage-report -reporttypes:"Cobertura"'
                displayName: "Create coverage reports"
              - task: PublishCodeCoverageResults@1
                displayName: "Publish code coverage report"
                inputs:
                  codeCoverageTool: Cobertura
                  summaryFileLocation: "$(Build.SourcesDirectory)/coverage-report/Cobertura.xml"
